server:
  port: 8080
  servlet:
    session:
      timeout: 10s

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example_data?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  security:
    loginType: JSON
    user:
      name: admin
      password: admin

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.business.sys.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true